services:
  main:
    build:
      context: ${CONTEXT_DIR}
    image: ${MAIN_IMAGE_NAME}
    pull_policy: build
    command: [ "sh", "-c", "sleep infinity" ]
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 192.168.0.1
